//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAttachment
    {
        public System.Guid ID { get; set; }
        public System.Guid EmailQueueID { get; set; }
        public bool IsExistingFile { get; set; }
        public string Path { get; set; }
        public string AzureContainer { get; set; }
        public string FileID { get; set; }
        public string Filename { get; set; }
        public string Extension { get; set; }
        public string FileMediaType { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual EmailQueue EmailQueue { get; set; }
    }
}
