//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRole
    {
        public System.Guid MemberRoleID { get; set; }
        public Nullable<System.Guid> MemberID { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
    }
}
